name: exif_helper
description: "EXIF Helper"
publish_to: 'none'
version: 0.3.1

environment:
  sdk: ^3.10.0

dependencies:
  desktop_drop: ^0.6.0
  dropdown_button2: ^2.3.9
  expressions: ^0.2.5+2
  ffi: ^2.1.4
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  msix: ^3.16.12
  package_info_plus: ^8.3.0
  path: ^1.9.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: "PuHui"
      fonts:
        - asset: fonts/PuHuiTi-3-55-Regular.ttf
          weight: 400
        - asset: fonts/PuHuiTi-3-85-Bold.ttf
          weight: 700

msix_config:
  display_name: EXIF Helper
  publisher_display_name: ZhouCheng
  identity_name: ZhouCheng.EXIFHelper
  trim_logo: false
  msix_version: 0.3.0.0
  logo_path: assets/icon.png
  capabilities: internetClient
  languages: zh-cn, en-us, zh-tw
  publisher: # Publisher HERE
  store: true
